# Generated by Django 6.1.1 on 2026-09-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "verbose_name": "Commentary",
                "verbose_name_plural": "Commentaries",
            },
        ),
    ]
