# Generated by Django 6.1.1 on 2026-09-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_commentary_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentaries",
                to="blog.post",
            ),
            preserve_default=False,
        ),
    ]
